fix: extensive loading harmonization config
certat/intelmq-webinput-csv pull request #80
Opened 2022-10-27 14:59 UTC by rkokkelk

When `Event` is init, it automatically loads the harmonization config file. This means that for every event uploaded, the entire harmonization config file is loaded and parsed. This dramatically extends the time needed to parse a single event.

This PR ensures that the harmonization file is only loaded once and then used for generating all `Event` objects.

Fixes: #79

2022-10-27 15:14 UTC, sebix requested changes
Thank you for finding this performance bottleneck and providing the fix!

I suggest to load the harmonization directly from the file and not to extract it from the class

2022-10-27 15:14 UTC, sebix commented on intelmq_webinput_csv/bin/backend.py
> +    harmonization_config['event'] = Event().harmonization_config
```suggestion
    harmonization = load_configuration(HARMONIZATION_CONF_FILE)
```

And at the top of the file:
```python
from intelmq.lib.utils import RewindableFileHandle, load_configuration # the line exists partially, add load_configuration to it
from intelmq import HARMONIZATION_CONF_FILE
```

2022-10-27 15:39 UTC, rkokkelk commented on intelmq_webinput_csv/bin/backend.py
> +    harmonization_config['event'] = Event().harmonization_config
Done

2022-10-27 15:41 UTC, rkokkelk commented
Is any further improvement on the efficiency of submitting the files appreciated. Mainly thinking about using Python concurrent features to parallelize the generating of the `raw_message`. If this is appreciated, I'll look into create a separate PR for it.

2022-10-27 16:38 UTC, sebix commented
Keep in mind that there's [a fork](https://github.com/Intevation/intelmq-webinput-csv) which has not all the features of this repo (e.g. fieldnames are fixed) but it's backend is completely re-written.

2022-10-27 17:45 UTC, rkokkelk commented
I'm familiar with the fork. however, due to it being more JS heavy, we encountered more issues with it when handling very large files. We therefore shifted our focus on the original.

2022-11-01 20:26 UTC, sebix commented
> I'm familiar with the fork. however, due to it being more JS heavy, we encountered more issues with it when handling very large files.

Another reasons why it's "only" a fork. However it has CSRF protection and offers authentication (same as the manager), which is a must criterium in some organizations.

2022-11-09 10:59 UTC, aaronkaplan commented
Yup, but I guess you can wrap authentication around it via reverse proxies.

@RoyK: I'd be super interested in an improvement. Especially in my experience the parsing detection of what is what field type is sometimes problematic.

I'd say go for it if you have the resources. Thanks a lot!!


> On 01.11.2022, at 21:26, Sebastian ***@***.***> wrote:
> 
> 
> I'm familiar with the fork. however, due to it being more JS heavy, we encountered more issues with it when handling very large files.
> 
> Another reasons why it's "only" a fork. However it has CSRF protection and offers authentication (same as the manager), which is a must criterium in some organizations.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
>

2022-11-09 12:05 UTC, rkokkelk commented
Okay awesome, could you then maybe look into the already open PR which will at least greatly increase the overall processing time for uploading events into IntelMQ.

2022-11-18 12:22 UTC, merged